all: takeTurns1.c takeTurns2.c takeTurns3.c twoProducers.c
		gcc -pthread -o takeTurns1 takeTurns1.c
		gcc -pthread -o takeTurns2 takeTurns2.c
		gcc -pthread -o takeTurns3 takeTurns3.c
		gcc -pthread -o twoProducers twoProducers.c
clean:  
		rm takeTurns? 
			rm twoProducers
